import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const KEY='vela-v3';
const defaults={name:'새 캐릭터',description:'캐릭터의 성격과 기본 설정을 입력하세요.',note:'',rules:'',temperature:.8,maxTokens:700,reasoning:0,summaryInterval:10,summary:''};
const models=[{id:'openrouter-free',name:'OpenRouter 무료',reasoning:true},{id:'openrouter-auto',name:'OpenRouter 자동',reasoning:true}];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{characters:[],selected:null,apiKey:'',model:'openrouter-free',chats:{}}}catch{return {characters:[],selected:null,apiKey:'',model:'openrouter-free',chats:{}}}}
function App(){const [db,setDb]=useState(load);const [screen,setScreen]=useState('home');const [draft,setDraft]=useState(defaults);const [messages,setMessages]=useState([]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [menu,setMenu]=useState(false);const [settings,setSettings]=useState(false);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify(db)),[db]);
const character=useMemo(()=>db.characters.find(x=>x.id===db.selected),[db]);
useEffect(()=>{if(character){setMessages(db.chats[character.id]||[]);setDraft(character)}},[db.selected]);
function openCreate(){setDraft({...defaults,id:crypto.randomUUID()});setScreen('create')}
function saveCharacter(){const c={...draft};setDb(d=>({...d,characters:d.characters.some(x=>x.id===c.id)?d.characters.map(x=>x.id===c.id?c:x):[...d.characters,c],selected:c.id}));setScreen('chat');setMessages(db.chats[c.id]||[])}
function select(id){setDb(d=>({...d,selected:id}));setScreen('chat')}
function systemText(){return `캐릭터: ${draft.name}\n설정: ${draft.description}\n\n{user} 사용자 설정/노트:\n${draft.note||'(없음)'}\n\n추가 규칙:\n${draft.rules||'(없음)'}`}
async function send(){if(!input.trim()||busy||!character)return;const text=input.trim();const next=[...messages,{role:'user',content:text}];setMessages(next);setInput('');setBusy(true);try{if(!db.apiKey)throw new Error('OpenRouter API 키를 설정해주세요.');const body={model:db.model==='openrouter-auto'?'openrouter/free':'openrouter/free',messages:[{role:'system',content:systemText()},...next.slice(-20).map(m=>({role:m.role,content:m.content}))],temperature:draft.temperature,max_tokens:Number(draft.maxTokens)||700};if(Number(draft.reasoning)>0)body.reasoning={max_tokens:Number(draft.reasoning)};const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${db.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`API 오류 ${r.status}`);const reply=j.choices?.[0]?.message?.content||'응답이 없습니다.';const done=[...next,{role:'assistant',content:reply}];setMessages(done);setDb(d=>({...d,chats:{...d.chats,[character.id]:done}}));if(done.filter(x=>x.role==='user').length%Number(draft.summaryInterval)===0) generateSummary(done);}catch(e){setMessages(x=>[...x,{role:'system',content:`오류: ${e.message}`}])}finally{setBusy(false)}}
async function generateSummary(hist){if(!db.apiKey)return;try{const r=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${db.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:'openrouter/free',messages:[{role:'system',content:'대화 세션을 짧게 요약하세요. 다음 대화에서 기억해야 할 사실, 관계, 진행 상황만 정리하세요.'},{role:'user',content:hist.slice(-20).map(m=>`${m.role}: ${m.content}`).join('\n')}],max_tokens:350,temperature:.2})});const j=await r.json();const s=j.choices?.[0]?.message?.content;if(s)setDraft(c=>{const n={...c,summary:s};setDb(d=>({...d,characters:d.characters.map(x=>x.id===c.id?n:x)}));return n});}catch{}}
return <div className="app"><header><button onClick={()=>setMenu(!menu)}>☰</button><b>VELA</b><button onClick={()=>setScreen('home')}>⌂</button></header>{screen==='home'&&<Home db={db} select={select} create={openCreate}/>} {screen==='chat'&&character&&<Chat character={character} messages={messages} input={input} setInput={setInput} send={send} busy={busy} menu={()=>setMenu(true)}/>} {screen==='create'&&<Create draft={draft} setDraft={setDraft} save={saveCharacter} back={()=>setScreen(character?'chat':'home')}/>} {menu&&<Drawer close={()=>setMenu(false)} db={db} setDb={setDb} create={openCreate} edit={()=>{setDraft(character||defaults);setScreen('create');setMenu(false)}} settings={()=>setSettings(true)}/>} {settings&&<Settings draft={draft} setDraft={setDraft} close={()=>setSettings(false)}/>}</div>}
function Home({db,select,create}){return <main className="home"><div className="hero"><span>VELA CHAT</span><h1>대화할 캐릭터를<br/>선택하세요.</h1></div><button className="primary" onClick={create}>＋ 캐릭터 만들기</button><section><div className="sectionTitle">내 캐릭터</div>{db.characters.length?<div className="cards">{db.characters.map(c=><button className="card" key={c.id} onClick={()=>select(c.id)}><strong>{c.name}</strong><small>{c.description}</small></button>)}</div>:<div className="empty">아직 만든 캐릭터가 없습니다.</div>}</section></main>}
function Chat({character,messages,input,setInput,send,busy}){return <main className="chat"><div className="chatTitle"><strong>{character.name}</strong><small>{character.description}</small></div><div className="messages">{!messages.length&&<div className="welcome">접속 시작<br/><small>대화를 입력해보세요.</small></div>}{messages.map((m,i)=><div key={i} className={'msg '+m.role}><span>{m.content}</span></div>)}{busy&&<div className="msg assistant"><span>생각하는 중…</span></div>}</div><div className="composer"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="메시지 보내기"/><button onClick={send} disabled={busy}>↑</button></div></main>}
function Create({draft,setDraft,save,back}){const f=(k)=><input value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>;return <main className="page"><div className="pageHead"><button onClick={back}>‹</button><strong>캐릭터 제작</strong></div><label>이름{f('name')}</label><label>캐릭터 설정<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>유저노트<textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/><small>{'{user}'}의 설정과 AI에게 전달할 추가 정보</small></label><label>추가 규칙<textarea value={draft.rules} onChange={e=>setDraft({...draft,rules:e.target.value})}/></label><button className="primary" onClick={save}>저장하고 시작</button></main>}
function Settings({draft,setDraft,close}){return <div className="overlay"><div className="modal"><div className="modalHead"><strong>채팅 설정</strong><button onClick={close}>×</button></div><label>출력 토큰<input type="number" value={draft.maxTokens} onChange={e=>setDraft({...draft,maxTokens:e.target.value})}/></label><label>추론량<input type="number" value={draft.reasoning} onChange={e=>setDraft({...draft,reasoning:e.target.value})}/></label><label>요약 메모리 주기<select value={draft.summaryInterval} onChange={e=>setDraft({...draft,summaryInterval:e.target.value})}><option value="10">10턴</option><option value="15">15턴</option><option value="20">20턴</option></select></label><label>온도<input type="number" step=".1" value={draft.temperature} onChange={e=>setDraft({...draft,temperature:e.target.value})}/></label>{draft.summary&&<div className="summary"><b>최근 요약</b><p>{draft.summary}</p></div>}</div></div>}
function Drawer({close,db,setDb,create,edit,settings}){return <div className="overlay"><aside className="drawer"><button onClick={close}>×</button><h2>Vela</h2><button onClick={create}>＋ 캐릭터 제작</button><button onClick={edit}>캐릭터 설정</button><button onClick={settings}>채팅 설정</button><label>OpenRouter API Key<input type="password" value={db.apiKey} onChange={e=>setDb({...db,apiKey:e.target.value})}/></label><small>무료 라우터도 API 키가 필요합니다.</small></aside></div>}
createRoot(document.getElementById('root')).render(<App/>);
